name: deploy to production
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: pull
      run: |
        cd /home/fgf/fgf-site/prod
        git stash
        git pull origin master